/*
 * generated by Xtext 2.38.0
 */
package org.sculptor.dsl.web

import com.google.inject.Guice
import com.google.inject.Injector
import org.eclipse.xtext.util.Modules2
import org.sculptor.dsl.SculptordslRuntimeModule
import org.sculptor.dsl.SculptordslStandaloneSetup
import org.sculptor.dsl.ide.SculptordslIdeModule

/**
 * Initialization support for running Xtext languages in web applications.
 */
class SculptordslWebSetup extends SculptordslStandaloneSetup {
	
	override Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SculptordslRuntimeModule, new SculptordslIdeModule, new SculptordslWebModule))
	}
	
}
