/*
 * generated by Xtext 2.38.0
 */
package org.sculptor.dsl.web

/**
 * Use this class to register additional components to be used within the web application.
 */
class SculptordslWebModule extends AbstractSculptordslWebModule {
}
