/*
 * generated by Xtext
 */
package org.sculptor.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SculptordslRuntimeModule extends org.sculptor.dsl.AbstractSculptordslRuntimeModule {

}
