<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.sculptorgenerator</groupId>
		<artifactId>sculptor-generator</artifactId>
		<version>4.0.0-SNAPSHOT</version>
	</parent>
	<groupId>org.sculptorgenerator.generator</groupId>
	<artifactId>sculptor-metamodel</artifactId>
	<!--
	<packaging>eclipse-plugin</packaging>
	-->
	<name>Sculptor :: Generator :: Metamodel</name>

  <build>
    <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>src</source>
                                <source>src-gen</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
    </plugins>
  </build>
	<dependencies>
		<dependency>
			 <groupId>org.eclipse.emf</groupId>
			 <artifactId>org.eclipse.emf.ecore</artifactId>
			 <version>${xtext-version}</version>
		</dependency>
	</dependencies>
</project>
