/*
* generated by Xtext
*/
package org.sculptor.dsl.ui.contentassist;

import org.sculptor.dsl.ui.contentassist.AbstractSculptordslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SculptordslProposalProvider extends AbstractSculptordslProposalProvider {

}
