/*
* generated by Xtext
*/
package org.sculptor.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SculptordslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
