package org.sculptor.generator.ext;

import org.sculptor.generator.template.service.ServiceTmpl;
import org.sculptor.generator.template.service.ServiceEjbTestTmpl;
import org.sculptor.generator.template.service.ServiceTestTmpl;
import org.sculptor.generator.template.service.ServiceEjbTmpl;
import org.sculptor.generator.template.web.JSFCrudGuiConfigContextTmpl;
import org.sculptor.generator.template.drools.DroolsTmpl;
import org.sculptor.generator.template.doc.ModelDocTmpl;
import org.sculptor.generator.template.doc.UMLGraphTmpl;
import org.sculptor.generator.template.doc.ModelDocCssTmpl;
import org.sculptor.generator.template.spring.SpringTmpl;
import org.sculptor.generator.template.springint.SpringIntegrationTmpl;
import org.sculptor.generator.template.db.DDLTmpl;
import org.sculptor.generator.template.db.MysqlDDLTmpl;
import org.sculptor.generator.template.db.OracleDDLTmpl;
import org.sculptor.generator.template.db.CustomDDLTmpl;
import org.sculptor.generator.template.db.DatasourceTmpl;
import org.sculptor.generator.template.db.DbUnitTmpl;
import org.sculptor.generator.template.domain.DomainObjectAnnotationTmpl;
import org.sculptor.generator.template.domain.DomainObjectReferenceAnnotationTmpl;
import org.sculptor.generator.template.domain.DomainObjectNamesTmpl;
import org.sculptor.generator.template.domain.DomainObjectConstructorTmpl;
import org.sculptor.generator.template.domain.DomainObjectTraitTmpl;
import org.sculptor.generator.template.domain.DomainObjectReferenceTmpl;
import org.sculptor.generator.template.domain.DomainObjectKeyTmpl;
import org.sculptor.generator.template.domain.DomainObjectPropertiesTmpl;
import org.sculptor.generator.template.domain.DomainObjectAttributeAnnotationTmpl;
import org.sculptor.generator.template.domain.DomainObjectAttributeTmpl;
import org.sculptor.generator.template.domain.BuilderTmpl;
import org.sculptor.generator.template.domain.DomainObjectTmpl;
import org.sculptor.generator.template.mongodb.MongoDbConversationDomainObjectRepositoryTmpl;
import org.sculptor.generator.template.mongodb.MongoDbServiceTestTmpl;
import org.sculptor.generator.template.mongodb.MongoDbMapperTmpl;
import org.sculptor.generator.template.jpa.EclipseLinkTmpl;
import org.sculptor.generator.template.jpa.DataNucleusTmpl;
import org.sculptor.generator.template.jpa.JPATmpl;
import org.sculptor.generator.template.jpa.OpenJpaTmpl;
import org.sculptor.generator.template.jpa.HibernateTmpl;
import org.sculptor.generator.template.camel.CamelTmpl;
import org.sculptor.generator.template.common.LogConfigTmpl;
import org.sculptor.generator.template.common.PubSubTmpl;
import org.sculptor.generator.template.common.ExceptionTmpl;
import org.sculptor.generator.template.consumer.ConsumerTmpl;
import org.sculptor.generator.template.consumer.ConsumerTestTmpl;
import org.sculptor.generator.template.consumer.ConsumerEjbTmpl;
import org.sculptor.generator.template.consumer.ConsumerEjbTestTmpl;
import org.sculptor.generator.template.repository.AccessObjectTmpl;
import org.sculptor.generator.template.repository.AccessObjectFactoryTmpl;
import org.sculptor.generator.template.repository.RepositoryTmpl;
import org.sculptor.generator.template.rest.RestWebCssTmpl;
import org.sculptor.generator.template.rest.RestWebJspTmpl;
import org.sculptor.generator.template.rest.ResourceTmpl;
import org.sculptor.generator.template.rest.RestWebConfigTmpl;
import org.sculptor.generator.template.rest.RestWebTmpl;
import org.sculptor.generator.template.RootTmpl;
import org.sculptor.generator.util.DbHelperBase;
import org.sculptor.generator.util.HelperBase;
import org.sculptor.generator.util.PropertiesBase;
import org.sculptor.generator.util.XmlHelperBase;

public interface GeneratorFactory {

	public Helper helper();
	public HelperBase helperBase();
	public Properties properties();
	public PropertiesBase propertiesBase();
	public DbHelperBase dbHelperBase();
	public DbHelper dbHelper();
	public XmlHelperBase xmlHelperBase();
	public UmlGraphHelper umlGraphHelper();

	public ServiceTmpl serviceTmpl();
	public ServiceEjbTestTmpl serviceEjbTestTmpl();
	public ServiceTestTmpl serviceTestTmpl();
	public ServiceEjbTmpl serviceEjbTmpl();
	public JSFCrudGuiConfigContextTmpl jSFCrudGuiConfigContextTmpl();
	public DroolsTmpl droolsTmpl();
	public ModelDocTmpl modelDocTmpl();
	public UMLGraphTmpl uMLGraphTmpl();
	public ModelDocCssTmpl modelDocCssTmpl();
	public SpringTmpl springTmpl();
	public SpringIntegrationTmpl springIntegrationTmpl();
	public DDLTmpl dDLTmpl();
	public MysqlDDLTmpl mysqlDDLTmpl();
	public OracleDDLTmpl oracleDDLTmpl();
	public CustomDDLTmpl customDDLTmpl();
	public DatasourceTmpl datasourceTmpl();
	public DbUnitTmpl dbUnitTmpl();
	public DomainObjectAnnotationTmpl domainObjectAnnotationTmpl();
	public DomainObjectReferenceAnnotationTmpl domainObjectReferenceAnnotationTmpl();
	public DomainObjectNamesTmpl domainObjectNamesTmpl();
	public DomainObjectConstructorTmpl domainObjectConstructorTmpl();
	public DomainObjectTraitTmpl domainObjectTraitTmpl();
	public DomainObjectReferenceTmpl domainObjectReferenceTmpl();
	public DomainObjectKeyTmpl domainObjectKeyTmpl();
	public DomainObjectPropertiesTmpl domainObjectPropertiesTmpl();
	public DomainObjectAttributeAnnotationTmpl domainObjectAttributeAnnotationTmpl();
	public DomainObjectAttributeTmpl domainObjectAttributeTmpl();
	public BuilderTmpl builderTmpl();
	public DomainObjectTmpl domainObjectTmpl();
	public MongoDbConversationDomainObjectRepositoryTmpl mongoDbConversationDomainObjectRepositoryTmpl();
	public MongoDbServiceTestTmpl mongoDbServiceTestTmpl();
	public MongoDbMapperTmpl mongoDbMapperTmpl();
	public EclipseLinkTmpl eclipseLinkTmpl();
	public DataNucleusTmpl dataNucleusTmpl();
	public JPATmpl jPATmpl();
	public OpenJpaTmpl openJpaTmpl();
	public HibernateTmpl hibernateTmpl();
	public CamelTmpl camelTmpl();
	public LogConfigTmpl logConfigTmpl();
	public PubSubTmpl pubSubTmpl();
	public ExceptionTmpl exceptionTmpl();
	public ConsumerTmpl consumerTmpl();
	public ConsumerTestTmpl consumerTestTmpl();
	public ConsumerEjbTmpl consumerEjbTmpl();
	public ConsumerEjbTestTmpl consumerEjbTestTmpl();
	public AccessObjectTmpl accessObjectTmpl();
	public AccessObjectFactoryTmpl accessObjectFactoryTmpl();
	public RepositoryTmpl repositoryTmpl();
	public RootTmpl rootTmpl();
	public RestWebCssTmpl restWebCssTmpl();
	public RestWebJspTmpl restWebJspTmpl();
	public ResourceTmpl resourceTmpl();
	public RestWebConfigTmpl restWebConfigTmpl();
	public RestWebTmpl restWebTmpl();
}