/*
 * generated by Xtext 2.12.0
 */
package org.sculptor.dsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.^extension.ExtendWith;
import org.sculptor.dsl.sculptordsl.DslModel

import static org.junit.jupiter.api.Assertions.*;

@ExtendWith(typeof(InjectionExtension))
@InjectWith(SculptordslInjectorProvider)
class SculptordslParsingTest {

	@Inject ParseHelper<DslModel> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			ApplicationPart Test {
				
				Module mod {
					Entity Test {}
				}
				
			}
		''')
		assertNotNull(result)
		assertTrue(result.eResource.errors.isEmpty)
	}
}
